apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-web
  labels:
    name: laravel-web
spec:
  replicas: 3
  selector:
    matchLabels:
      name: laravel-web
  template:
    metadata:
      name: laravel-web
      labels:
        name: laravel-web
    spec:
      containers:
        - name: laravel-web
          image: indragiri21/laravel-jenkins:buildNumber
          ports:
            - containerPort: 8000

---

apiVersion: v1
kind: Service
metadata:
  name: laravel-env-service
spec:
  selector:
    name: laravel-web
  ports:
    - port: 8000
      targetPort: 8000
  type: LoadBalancer
